<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    //'Twig_' => array($vendorDir . '/twig/twig/lib'), // не работает
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
    'Core' => array($baseDir . '/Core'),
    'Zoqa' => array($baseDir . '/Core'),
    //'Application\Users' => array($baseDir . '/Core/Model/Users'),
    //'Testspace' => array($baseDir . '/Core/Helper'), // не работает
    //'Yandex' => array($vendorDir . '/Yandex'), // не работает
    'Yandex' => array($baseDir . '/Core/Model/Yandex'), //  работает
    //'Application\Categories' => array($baseDir . '/Core/Model/Categories'), // не работает
    //'Application\Config' => $baseDir . '/Core/Model/Config', // не работает

);