<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

/**
 * [!] $baseDir указывает на корень сайта: C:\wamp\www\zoqa
 */

return array(
    'Bluz\\Tests\\'     => array($baseDir . '/lib/bluz/tests/src'),
    'Bluz\\'            => array($baseDir . '/lib/bluz'),
    'Zoqa\\Testspace\\' => array($baseDir . '/Core/Helper'), // работает
    'Application\\Test\\' => array($baseDir . '/Core/Model/Test'), // работает
);
