<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/FirePHP/firephp-core/lib/FirePHPCore/fb.php', // работает
    $vendorDir . '/bluz/_functions.php',
    $vendorDir . '/bluz/_loader.php',
);
