{#
/**
 * @var \Bluz\Grid\Grid $grid
 */
#}
{#
    <?php if ($grid->pages() > 1 && sizeof($grid->getData()) < $grid->getLimit()) :
    $emptyRows = $grid->getLimit() - sizeof($grid->getData()); ?>

#}
    <table class="table">
        {% for item in emptyRows %}
        {#<?php for ($i = 0; $i < $emptyRows; $i++): ?> #}
            <tr>
                <td>&nbsp;</td>
            </tr>
        {% endfor %}
    </table>
{#
    <?php endif; ?>
#}