{#
/**
 * @var \Bluz\Grid\Grid $grid
 */

{% set foo = 'foo' %}

#}



{#<?php if ($grid->pages() > 1) : ?>#}
{% if grid.pages > 1 %}
    <ul class="pagination pull-right">
        {% if grid.prev %}
            <li><a href="{{ grid.prev }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#" onclick="javascript:return false;">&laquo;</a></li>
        {% endif %}

        {#
        <?php if ($prev = $grid->prev()) : ?><li><a href="<?=$prev?>">&laquo;</a></li>
        <?php else : ?> <li class="disabled"><a href="#" onclick="javascript:return false;">&laquo;</a></li>
        <?php endif; ?>
        #}

        {% for p in grid.pages %}
            <li {{ p == grid.getPage ? 'class="active"' : '' }}>
                <a href="{{ grid.page(p) }}">{{ p }}</a></li>
            {#
            <?php for ($page = 1; $page <= $grid->pages(); $page++) : ?>
                <li <?=($page==$grid->getPage()?'class="active"':'') ?>><a href="<?=$grid->page($page)?>"><?=$page?></a></li>
            <?php endfor; ?>
            #}
        {% endfor %}

        {# <?php if ($next = $grid->next()) : ?><li><a href="<?=$next?>">&raquo;</a></li> #}
        {% if grid.next() %}
            <li><a href="{{ grid.next }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#" onclick="javascript:return false;">&raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}
