<?php
/**
 * @var \Application\Users\Row $user
 * @var \Bluz\View\View $this
 */
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{{ __('Авторизуйтесь, пожалуйста') }}</h3>
    </div>
    <form action="{{ url('users', 'signin') }}" method="post">
    <div class="panel-body">

            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                <input type="text" name="login" class="form-control" value="{{ login }}" placeholder="{{ __('login') }}" maxlength="255" required />
            </div>

            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
                <input type="password" name="password" class="form-control" placeholder="{{ __('password') }}" required />
            </div>



    </div>
    <div class="panel-footer clearfix">
        <div class="pull-left">
            <input type="submit" value="{{ __('Войти') }}" class="btn btn-primary"/>
            {#
            <a href="{{ url('users', 'signup') }}" title="Sign Up" class="btn btn-default pull-right">{{ __('Зарегистрироваться') }}</a>
            #}

            {# widget('vk', 'auth') #}
        </div>
        <!--div class="pull-left">
            {# widget('facebook', 'auth') #}
        </div-->
        {#
        <a href="{{ url('users', 'recovery') }}" class="pull-right">{{ __('Забыли пароль?') }}</a>
        #}
    </div>
    </form>


</div>
