{% set uid = uniqid('form_') %}

{# action="{{ url('admin', 'ajax/crud') }}" #}
{# action="{{ url('admin', 'categories-crud')  }}" #}
<form id="{{ uid }}" action="{{ url('admin', 'categories-crud') }}" class="form-horizontal ajax" method="{{ method }}">
    <input type="hidden" name="categories_id" value="{{ row.categories_id }}"/>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Категория товаров</h3>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="categories_name">{{ __('Название') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="categories_name" name="categories_name" value="{{ row.categories_name }}" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="categories_seo_page_name">{{ __('СЕО-имя') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="categories_seo_page_name" name="categories_seo_page_name" value="{{ row.categories_seo_page_name }}" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="categories_seo_page_name">{{ __('Наценка (%)') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="price_index" name="price_index" value="{{ row.price_index }}" required />
            </div>
        </div>
        <!--div class="form-group">
            <label class="control-label col-lg-2" for="status">{{ __('Status') }}</label>
            <div class="col-lg-10">
                <select id="status" name="status" class="form-control">
                    <option {% if row.status == 'active' %} 'selected' {% endif %}>active</option>
                </select>
            </div>
        </div-->
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">{{ __('Сохранить') }}</button>
        <a href="#" class="btn btn-default" data-dismiss="modal">{{ __('Отмена') }}</a>
    </div>
</form>

{% if errors %}
Error

{% endif %}