<script>
    require(["bluz.grid"]);
</script>

<div class="clearfix" data-spy="grid" data-grid="{{ attribute(grid, 'getUid')  }}" data-url="admin/grid-categories">


    <form class="filter-form" action="admin/grid-categories">
    <div class="input-group-btn grid-filter-search">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Поле для поиска <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="#" data-filter="{{ grid.getUid }}-filter-categories_name"> Название </a></li>
                <li><a href="#" data-filter="{{ grid.getUid }}-filter-categories_seo_page_name"> СЕО </a></li>
            </ul>
        </div><!-- /btn-group -->
        <input name="grid-filter-categories_name" class="grid-filter-search-input" value="" type="hidden"/>
        <input name="grid-filter-categories_seo_page_name" class="grid-filter-search-input" value="" type="hidden"/>

        <input name="search-like" type="search" class="form-control" value="" required />
    </form>


<div class="input-group">
    <a href="{{ url('admin', 'categories-crud') }}" class="btn btn-primary pull-left dialog" data-ajax-method="get">Создать</a>
</div>
  
    {# grid.getUrl() #}

{{ partial('grid/limit.phtml', {'grid': grid}) }}

<table class="table grid">
    <thead>
    <tr>
        <th width="50px"><a href="{{ grid.order('categories_name', null, 'desc', false) }}">Название</a></th>
        <th width="50px"><a href="{{ grid.order('sort_order') }}">Порядок</a></th>
        <th width="120px"><a href="{{ grid.order('price_index') }}">Наценка</a></th>
        <th width="120px"><a href="{{ grid.order('categories_status') }}">Статус</a></th>
        <th width="120px"><a href="{{ grid.order('categories_seo_page_name') }}">СЕО</a></th>
        <th width="120px">Действия</th>
    </tr>
    </thead>
    <tbody>
    {% for row in attribute(grid, 'getData') %}
    <tr>
        <td>{{ row['categories_name'] }}</td>
        <td>{{ row['sort_order'] }}</td>
        <!--td>{{ row['date_added']|date("j F G:i ") }}</td-->
        <td>
            {% if( row['price_index'] > 0 ) %}
                 {{ row['price_index'] }}
            {% endif %}
        </td>
        <td>{{ row['categories_status'] }}</td>
        <td>{{ row['categories_seo_page_name'] }}</td>
        <td class="controls">
            <a href="{{ url('admin', 'categories-crud', {'categories_id' : row['categories_id']}) }}" class="btn btn-xs btn-primary dialog" data-ajax-method="get">
                <i class="fa fa-pencil"></i>
            </a>
            <!--a href="{{ url('admin', 'categories-crud', {'categories_id' : row['categories_id']}) }}" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                <i class="fa fa-times"></i>
            </a-->
            {# set asd = grid.getUid ~ '-filter-parent_id' #}
            {% if(row['parent_id'] == 0) %}
                <a href="{{ url('admin', 'grid-categories', {  'sql-filter-parent_id': row['categories_id']}) }}" class="confirm filter btn btn-xs btn-default ajax" data-ajax-method="get">
                    <i class="fa fa-table"></i>
                </a>
            {% else %}
                <a href="{{ url('admin', 'grid-categories') }}" class="confirm filter btn btn-xs btn-default ajax" data-ajax-method="get">
                    <i class="fa fa-table"></i>
                </a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>




{{ partial('grid/empty-rows.phtml', {'grid': grid}) }}
{{ partial('grid/pagination.phtml', {'grid': grid}) }}
{{ partial('grid/total.phtml', {'grid': grid}) }}



</div>

