<script>
    require(["bluz.grid"]);
</script>


<div class="clearfix" data-spy="grid" data-grid="{{ attribute(grid, 'getUid')  }}"
     data-url="{{ baseUrl('admin/grid-users') }}">


    <form class="filter-form" action="{{ baseUrl('/admin/grid-users') }}">
        <div class="input-group-btn grid-filter-search">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ field }} <span
                    class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for column,filtertitle in filters %}
                <li><a href="#" data-filter="{{ grid.getUid }}-filter-{{ column }}"> {{ filtertitle }} </a></li>
                {% endfor %}
            </ul>
        </div>
        <!-- /btn-group -->
        <input name="{{ grid.getUid }}-filter-{{ field }}" class="grid-filter-search-input"
               value="{{ type }}-{{ value }}" type="hidden"/>

        <input name="search-like" type="search" class="form-control" value="{{ value }}" required/>
    </form>


    <!--div class="input-group">
        <a href="{{ url('admin', 'users-crud') }}" class="btn btn-primary pull-left dialog" data-ajax-method="get">Создать</a>
    </div-->

    {# grid.getUrl() #}

    {{ partial('grid/limit.phtml', {'grid': grid}) }}

    <table class="table grid">
        <thead>
        <tr>
            <th width="60px"><a href="{{ grid.order('id', null, 'desc', false) }}">Id</a></th>
            <th width="80px"><a href="{{ grid.order('login') }}">Логин</a></th>
            <th width="80px"><a href="{{ grid.order('name') }}">Имя</a></th>
            <th width="80px"><a href="{{ grid.order('phone') }}">Телефон</a></th>
            <th width="120px"><a href="{{ grid.order('email') }}">Адрес почты</a></th>
            <th width="120px"><a href="{{ grid.order('status') }}">Статус</a></th>
            <th width="50px"><a href="{{ grid.order('credit') }}">Кредит</a></th>
            <th width="50px"><a href="{{ grid.order('discount') }}">Скидка</a></th>
            <th width="120px"><a href="{{ grid.order('orders_to_bonus') }}">До подарка заказов</a></th>
            <th width="50px"><a href="{{ grid.order('presents') }}">Заработал подарков</a></th>
            <th width="100px">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for row in attribute(grid, 'getData') %}
        <tr>
            <td>{{ row['id'] }}</td>
            <td>{{ row['login'] }}</td>
            <td>{{ row['name'] }}</td>
            <td>{{ row['phone'] }}</td>
            <td>{{ row['email'] }}</td>
            <td>
                {% if(row['status'] == 'active') %}
                Активен
                {% elseif(row['status'] == 'disabled') %}
                Заблокирован
                {% elseif(row['status'] == 'pending') %}
                В процессе регистрации
                {% endif %}
            </td>
            <td>{{ row['credit']|round(2, 'ceil') }}</td>
            <td>{{ row['discount'] }}</td>
            <td>{{ row['orders_to_bonus'] }}</td>
            <td>{{ row['presents'] }}</td>
            <td class="controls">
                {% if( row.login == 'system' ) %}
                {% elseif( row.login == 'admin') %}
                {% else %}
                <a href="{{ url('admin', 'users-crud', {'id' : row['id']}) }}" class="btn btn-xs btn-primary dialog"
                   data-ajax-method="get">
                    <i class="fa fa-pencil"></i>
                </a>
                <!--a href="{{ url('admin', 'user-crud', {'id' : row['id']}) }}" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                    <i class="fa fa-times"></i>
                </a-->
                {# set asd = grid.getUid ~ '-filter-parent_id' #}
                {#
                {% if(row['parent_id'] == 0) %}
                <a href="{{ url('admin', 'grid-categories', {  'sql-filter-parent_id': row['categories_id']}) }}"
                   class="confirm filter btn btn-xs btn-default ajax" data-ajax-method="get">
                    <i class="fa fa-table"></i>
                </a>
                {% else %}
                <a href="{{ url('admin', 'grid-categories') }}" class="confirm filter btn btn-xs btn-default ajax"
                   data-ajax-method="get">
                    <i class="fa fa-table"></i>
                </a>
                {% endif %}
                #}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


    {{ partial('grid/empty-rows.phtml', {'grid': grid}) }}
    {{ partial('grid/pagination.phtml', {'grid': grid}) }}
    {{ partial('grid/total.phtml', {'grid': grid}) }}


</div>

