{% set uid = uniqid('form_') %}


{#<form id="{{ uid }}" action="{{ url('admin', 'products-crud') }}" class="form-horizontal ajax" method="{{ method }}">#}


{# Форма загрузки титульной картинки #}
<form action="{{ baseUrl('admin') }}/upload-image/products_id/{{ row.products_id }}" enctype="multipart/form-data" method="post"   data-id="{{ row.products_id }}" name="title-image-form-{{ row.products_id }}" id="{{ uid }}" class="title-image-form form-horizontal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title"> {{ row.products_name }} </h3>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="title-image">Картинка</label>
            <div class="controls col-lg-10">
                <div style="display:none" name="formloading"><img alt="Загрузка...." src="{{ baseUrl('public/images/loader_2.gif') }}"></div>
                <div id="imgloadbutton-2">
                    <input type="file"   name="title-image" class="filestyle" data-icon="true" data-buttonText="Выбрать файл">
                </div>
                <p class="help-block">Изображение продукта</p>
            </div>
        </div>
        <input type="hidden" name="products_id" value="{{ row.products_id }}"/>

        <div class="form-group">
            <label class="control-label col-lg-2" for="squarify">{{ __('Обрезать под квадрат') }}</label>
            <div class="col-lg-10">
                <input type="checkbox" name="squarify" checked="checked">
            </div>
        </div>

    </div>

    <!--
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Заказ</h3>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="address">{{ __('Адрес доставки') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="address" name="address" value="{{ row.address }}" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="notes">{{ __('Замечания') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="notes" name="notes" value="{{ row.notes }}" required />
            </div>
        </div-->
        <!--div class="form-group">
            <label class="control-label col-lg-2" for="status">{{ __('Status') }}</label>
            <div class="col-lg-10">
                <select id="status" name="status" class="form-control">
                    <option {% if row.status == 'active' %} 'selected' {% endif %}>active</option>
                    <option {% if row.status == 'disable' %} 'selected' {% endif %}>disable</option>
                    <option {% if row.status == 'delete' %} 'selected' {% endif %}>delete</option>
                </select>
            </div>
        </div-->
    </div>

    <div name="preview" id="preview-{{ products_id }}" class="preview"></div>

    <div class="modal-footer">
        <button type="reset" class="btn btn-primary ok">{{ __('Применить') }}</button>
        <a href="#" class="btn btn-default" data-dismiss="modal">{{ __('Закрыть') }}</a>
    </div>

</form>




{% if errors %}
    Error

{% endif %}


    <script>
        require(["jquery", "jquery.form", "bluz", "filestyle"],  function ($, jqueryform, bluz, filestyle) {
            $("form.title-image-form").find("button.ok").off().on("click",function(e){

                $(this).closest("form").find("button.close").click();
                $("div[data-spy=grid] ul.pager  li a").click()

            });

            $("input[name=title-image]").off("click").on("change", function(){

                var products_id = $(this).closest("form").attr("data-id")
                var squarify =  $(this).closest("form").find("input[name=squarify]").prop( "checked" )

                $("#preview").html("");
                $("form[name=title-image-form-"+products_id+"]").ajaxForm({
                    target: ".preview",
                    data: {"convert":squarify},
                    beforeSubmit:function(){
                        //console.log("s");
                        $("div[name=formloading]").show();
                        $("#imgloadstatus").show();
                        $("#imgloadbutton").hide();
                    },
                    success:function(){
                        //console.log("z");
                        $("#imgloadstatus").hide();
                        $("#imgloadbutton").show();
                    },
                    error:function(){
                        //console.log("d");
                        $("#imgloadstatus").hide();
                        $("#imgloadbutton").show();
                    },
                    complete:function(respObj){
                        if(respObj.statusText == "OK"){

                             if(respObj.responseJSON.ahref != undefined){
                             //$("form[name=add-edit-article-form] input[name=cover]").val(respObj.responseJSON.ahref);
                             $("div[name=preview]").html("<img src="+respObj.responseJSON.ahref+" style=height:150px; />")
                             }

                        }
                        $("div[name=formloading]").hide();
                        $("#imgloadstatus").hide();
                        $("#imgloadbutton").show();
                    }
                }).submit();
            });

        });
    </script>