{% set uid = uniqid('form_') %}


<form id="{{ uid }}" action="{{ url('admin', 'products-crud-2') }}" class="form-horizontal ajax" method="{{ method }}">
   <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3 class="modal-title"> {% if(row.products_name) %} {{ row.products_name }} {% else %} Новый продукт {% endif %}</h3>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label class="control-label col-lg-2" for="products_id">Артикул</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_id" name="products_id" value="{{ row.products_id }}" required />
                    </div>
                    <p class="help-block hb-2">Значение должно быть уникальным</p>
                </div>
            </div>
            <!--input type="hidden" name="products_id" value="{{ row.products_id }}"/-->
            <div class="form-group">
                <label class="control-label col-lg-2" for="products_barcode">Штрихкод</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_barcode" name="products_barcode" value="{{ row.products_barcode }}" required />
                    </div>
                    <p class="help-block hb-2">Значение должно быть уникальным</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_name">Название</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_name" name="products_name" value="{{ row.products_name }}" required />
                    </div>
                    <p class="help-block hb-2"></p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="manufacturers_id">Произво-<br>дитель</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <!--input type="text" class="form-control" id="manufacturers_id" name="manufacturers_id" value="{{ row.manufacturers_id }}" required /-->
                        {{ manufacturers_select }}
                    </div>
                    <p class="help-block hb-2">Если производителя нет в списке, оставить Noname</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="categories_id">Категория</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <!--input type="text" class="form-control" id="manufacturers_id" name="manufacturers_id" value="{{ row.manufacturers_id }}" required /-->
                        {{ categories_select }}
                    </div>
                    <p class="help-block hb-2">Если производителя нет в списке, оставить Noname</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_seo_page_name">СЕО-имя</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_seo_page_name" name="products_seo_page_name" value="{{ row.products_seo_page_name }}"  />
                    </div>
                    <p class="help-block hb-2">Символическое имя продукта для ссылки на него</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_unit">Ед изм</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_unit" name="products_unit" value="{{ row.products_unit }}"  />
                    </div>
                    <p class="help-block hb-2">Единицы измерения, напр кг</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_shoppingcart_price">Розничная цена</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_shoppingcart_price" name="products_shoppingcart_price" value="{{ row.products_shoppingcart_price }}"  />
                    </div>
                    <p class="help-block hb-2">В формате 0.00</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_price">Оптовая цена</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_price" name="products_price" value="{{ row.products_price }}"  />
                    </div>
                    <p class="help-block hb-2">В формате 0.00</p>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="products_quantity">Остаток</label>
                <div class="controls col-lg-10">
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="products_quantity" name="products_quantity" value="{{ row.products_quantity }}"  />
                    </div>
                    <p class="help-block hb-2">Число в формате 0.00</p>
                </div>
            </div>



        </div>

        <!--
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Заказ</h3>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="address">{{ __('Адрес доставки') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="address" name="address" value="{{ row.address }}" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="notes">{{ __('Замечания') }}</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="notes" name="notes" value="{{ row.notes }}" required />
            </div>
        </div-->
        <!--div class="form-group">
            <label class="control-label col-lg-2" for="status">{{ __('Status') }}</label>
            <div class="col-lg-10">
                <select id="status" name="status" class="form-control">
                    <option {% if row.status == 'active' %} 'selected' {% endif %}>active</option>
                    <option {% if row.status == 'disable' %} 'selected' {% endif %}>disable</option>
                    <option {% if row.status == 'delete' %} 'selected' {% endif %}>delete</option>
                </select>
            </div>
        </div-->
        </div>


        <div class="modal-footer">
            <button type="submit" class="btn btn-primary ok">{{ __('Сохранить') }}</button>
            <a href="#" class="btn btn-default" data-dismiss="modal">{{ __('Закрыть') }}</a>
        </div>

    </form>