 {# TODO сделать формирование фильтров автоматом

    {% for row in attribute(grid, 'getFilters' ) %}
       <b>{{ row }}</b>
    {% endfor %}
    #}

<form class="filter-form" action="{{ baseUrl('/admin/grid-products') }}">
    <div class="input-group-btn grid-filter-search">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Поле для поиска <span class="caret"></span></button>
        <ul class="dropdown-menu">
            <li><a href="#" data-filter="{{ grid.getUid }}-filter-products_id"> Артикул </a></li>
            <li><a href="#" data-filter="{{ grid.getUid }}-filter-products_barcode"> Штрихкод </a></li>
            <li><a href="#" data-filter="{{ grid.getUid }}-filter-products_name"> Наименование </a></li>
        </ul>
    </div><!-- /btn-group -->
    <input name="grid-filter-products_id" class="grid-filter-search-input" value="" type="hidden"/>
    <input name="grid-filter-products_barcode" class="grid-filter-search-input" value="" type="hidden"/>
    <input name="grid-filter-products_name" class="grid-filter-search-input" value="" type="hidden"/>

    <input name="search-like" type="search" class="form-control" value="" required />
</form>

{#
<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
$filters;  // array [field=>title]
$field = key($filters);
$value = ''; // filter value

$gridFilters = $grid->getFilters();

foreach ($filters as $filterName => $filterTitle) {
    if (isset($gridFilters[$filterName][$grid::FILTER_LIKE])) {
        $field = $filterName;
        $value = $gridFilters[$filterName][$grid::FILTER_LIKE];
        break;
    }
}
?>
<div class="input-group-btn grid-filter-search">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?=$filters[$field]?> <span class="caret"></span></button>
    <ul class="dropdown-menu">
        <?php foreach($filters as $fieldName => $fieldTitle) :?>
        <li><a href="#" data-filter="<?=$grid->getUid() .'-filter-'. $fieldName ?>"><?=$fieldTitle?></a></li>
        <?php endforeach; ?>
    </ul>
</div><!-- /btn-group -->
<input name="<?=$grid->getUid() .'-filter-'. $field ?>" class="grid-filter-search-input" value="<?=$grid::FILTER_LIKE.'-'.esc($value)?>" type="hidden"/>
<input name="search-like" type="search" class="form-control" value="<?=esc($value)?>" required />
#}