 {# TODO сделать формирование фильтров автоматом

    {% for row in attribute(grid, 'getFilters' ) %}
       <b>{{ row }}</b>
    {% endfor %}
    #}

 <form class="filter-form" action="{{ grid.url() }}"> {# grid.getUrl({'a':1}) #}
     <div class="input-group-btn grid-filter-search _one-line">
         <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ default_filter.title }} <span class="caret"></span></button>
         <ul class="dropdown-menu">
             {% for column,filtertitle in filters %}
             <li><a href="#" data-filter="{{ grid.getUid }}-filter-{{ column }}"> {{ filtertitle }} </a></li>
             {% endfor %}
         </ul>
     </div>
     <input name="{{ grid.getUid }}-filter-{{ default_filter.key }}" class="grid-filter-search-input" value="{# type }}-{{ value #}" type="hidden"/>

     <input name="search-like" type="search" class="form-control _one-line-search" value="{# value #}" required/>
 </form>

{#
<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
$filters;  // array [field=>title]
$field = key($filters);
$value = ''; // filter value

$gridFilters = $grid->getFilters();

foreach ($filters as $filterName => $filterTitle) {
    if (isset($gridFilters[$filterName][$grid::FILTER_LIKE])) {
        $field = $filterName;
        $value = $gridFilters[$filterName][$grid::FILTER_LIKE];
        break;
    }
}
?>
<div class="input-group-btn grid-filter-search">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?=$filters[$field]?> <span class="caret"></span></button>
    <ul class="dropdown-menu">
        <?php foreach($filters as $fieldName => $fieldTitle) :?>
        <li><a href="#" data-filter="<?=$grid->getUid() .'-filter-'. $fieldName ?>"><?=$fieldTitle?></a></li>
        <?php endforeach; ?>
    </ul>
</div><!-- /btn-group -->
<input name="<?=$grid->getUid() .'-filter-'. $field ?>" class="grid-filter-search-input" value="<?=$grid::FILTER_LIKE.'-'.esc($value)?>" type="hidden"/>
<input name="search-like" type="search" class="form-control" value="<?=esc($value)?>" required />
#}