{#
<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
#}

{% set pages_total = grid.pages %}
{% set reset = grid.reset %}



<ul class="pager pull-left">
    <li>
        <a href="{{ grid.reset() }}" class="filter">{{ __('Всего записей: ') }}
            <strong>{{ grid.total }}</strong> <!-- {{ _n('record', 'records', grid.total) }} -->
            {{ _n("Страниц: #{pages_total} ", "on #{pages_total} pages", grid.pages, "<strong> #{grid.pages} </strong>") }}</a>
    </li>
    <li>
    </li>
</ul>

