 <div id="content">
                <div class="content-text">

                    <div class="slider not-slide">
                        <img src="public/images/напитки.png" />
                    </div><!-- slider -->



                    <div class="position-relative">
                        <div class="select-cabnet"><span> Цена:  <span>&#9660;</span>  </span>
                            <ul class="select-no-display">
                                <li><a href="">по убыванию</a></li>
                                <li><a href="">по возрастанию</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="position-relative">
                        <div class="select-cabnet"><span>Производитель:  <span>&#9660;</span>  </span>
                            <ul class="select-no-display">
                                <li><a href="">Производитель 1</a></li>
                                <li><a href="">Производитель 2</a></li>
                                <li><a href="">Производитель 3</a></li>
                                <li><a href="">Производитель 4</a></li>
                                <li><a href="">Производитель 5</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="wrapper-goods">

                        <div class="goods">
                            <div class="name">Чай Ahmad Tea Английский №1</div>
                            <div class="image-box">
                                <img src="public/images/goods1.jpg">
                            </div>
                            <div class="description">
                                <div class="weight">25*2г.</div>
                                <div class="cost">25,56грн.</div>
                                <div class="basket"><a href="" >В корзину</a></div>
                                <div class="number-arrow">
                                    <a class="inc"></a>
                                    <input type="number" min="1" value="1" class="num">
                                    <a class="dec"></a>
                                </div>
                                <div class="price">25,56грн.</div>
                            </div>
                        </div>

                        <div class="goods">
                            <div class="name">Чай Ahmad Tea Английский №1</div>
                            <div class="image-box">
                                <img src="public/images/goods1.jpg">
                            </div>
                            <div class="description">
                                <div class="weight">25*2г.</div>
                                <div class="cost">25,56грн.</div>
                                <div class="basket"><a href="" >В корзину</a></div>
                                <div class="number-arrow">
                                    <a class="inc"></a>
                                    <input type="number" min="1" value="1" class="num">
                                    <a class="dec"></a>
                                </div>
                                <div class="price">25,56грн.</div>
                            </div>
                        </div>

                        <div class="goods">
                            <div class="name">Чай Ahmad Tea Английский №1</div>
                            <div class="image-box">
                                <img src="public/images/goods1.jpg">
                            </div>
                            <div class="description">
                                <div class="weight">25*2г.</div>
                                <div class="cost">25,56грн.</div>
                                <div class="basket"><a href="" >В корзину</a></div>
                                <div class="number-arrow">
                                    <a class="inc"></a>
                                    <input type="number" min="1" value="1" class="num">
                                    <a class="dec"></a>
                                </div>
                                <div class="price">25,56грн.</div>
                            </div>
                        </div>

                    </div>


                </div>
            </div><!---------------content------------------------->
        </div>