
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <title>{{ title(zoqa_title) }}</title>
    <base href="{{ baseUrl() }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="profile" href="http://gmpg.org/xfn/11"/>
    <link rel="stylesheet" href="{{ baseUrl('/public/css/bootstrap.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/price.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/styles.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/print.css') }}" media="print" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/basket.css') }}"  />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/jcarousel.css') }}"  />
    <link rel="shortcut icon"  href="{{ baseUrl('/public/favicon.png') }}" type="image/png" />

    <script src="{{ baseUrl('/public/js/require.js') }}"></script>
    <script src="{{ baseUrl('/public/js/config.js') }}"></script>

    <script src="{{ baseUrl('/public/js/scripts/script.js') }}"></script>



    <!-----------------Юля-+++------------------------>
    {#

    <script src="{{ baseUrl('/public/js/scripts/script.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/jquery.min.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/custom_animations.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/custom_easing.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/jSlider.js') }}"></script>

    <script src="{{ baseUrl('/public/js/scripts/jquery.min.js') }}"></script>
    <script src="{{ baseUrl('/public/js/jcarousel.js') }}"></script>
    #}
    <!------------------------------------------>

    <!-- For IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="{{ baseUrl('/public/js/vendor/html5shiv.js') }}"></script>
    <script src="{{ baseUrl('/public/js/vendor/html5shiv-printshiv.js') }}"></script>
    <![endif]-->

    {{ headScript() }}
    {{ headStyle() }}
    {{ link() }}
    {{ meta() }}


    {{ trigger('header') }}
</head>
<body data-spy="scroll" data-bluz-module="{{ module() }}" data-bluz-controller="{{ controller() }}">
<!-----------------Юля------------------------->
 
<div id="wrapper">
    <header>
        <div class="wrapper-header">
            <div class="wrapper-header-text">
                <h1 class="logo"><a href="{{ baseUrl('/') }}"><img src="public/images/logo2.png"></a></h1>
                <div class="row">
                    <span class="phone-text">Заказ:</span>
                    <span class="phone"> (093) 123-51-40</span>
                    <span class="phone">(050) 403-11-33 </span>
                    <span class="phone-text">Доставка:</span>
                    <span class="phone">  (068) 611-11-49 </span>
                </div>
                <div class="search-wrapper">
                    <div class="search-wrapper-for-substrate">
                        <div class="search-substrate"> <input type="text" id="search-global-field"> </div>
                    </div>
                    <button class="search" id="search-global-btn">Искать</button>
                </div>
            </div>
        </div>
    </header>




    <!------------------------------------------>
    {# php if (app()->hasMessages()): #}

    {% if( hasMessages() ) %}
    {# JS not allow read headers of current request, only for XMLHTTPRequests :( #}

    <script>
        require(['bluz.notify'], function(notify) {
            notify.set({{ getMessages() }} );
        });

    </script>
    {% endif %}

    <script>
        require(["jquery"],  function ($) {

                $("#search-global-btn").off().on("click",function(e){
                    var search = $("#search-global-field").val()
                    window.location = "поиск/" + search
                });


                $("#search-global-field").on("keypress",function(e){
                    var code = e.keyCode || e.which;

                    if(code == 13){
                        var search = $("#search-global-field").val()
                        window.location = "поиск/" + search
                    }
                });

        });
    </script>

    <div id="loading_2" class="hidden">
        <img src="{{ baseUrl('public/images/loader_2.gif') }}">
    </div>

    <script>

/*
        require(["jquery","jcarousel" ], function(  $, jcarousel_obj  ) {
            var jcarousel = $('.jcarousel');

            jcarousel
                .on('jcarousel:reload jcarousel:create', function () {
                    var carousel = $(this),
                        width = carousel.innerWidth();



                    carousel.jcarousel('items').css('width', Math.ceil(width) + 'px');
                })
                .jcarousel({
                    wrap: 'circular'
                });

            $('.jcarousel-control-prev')
                .jcarouselControl({
                    target: '-=1'
                });

            $('.jcarousel-control-next')
                .jcarouselControl({
                    target: '+=1'
                });

            $('.jcarousel-pagination')
                .on('jcarouselpagination:active', 'a', function() {
                    $(this).addClass('active');
                })
                .on('jcarouselpagination:inactive', 'a', function() {
                    $(this).removeClass('active');
                })
                .on('click', function(e) {
                    e.preventDefault();
                })
                .jcarouselPagination({
                    perPage: 1,
                    item: function(page) {
                        return '<a href="#' + page + '">' + page + '</a>';
                    }
                });

            $('.jcarousel')
                .jcarousel({
                    // Core configuration goes here
                })
                .jcarouselAutoscroll({
                    interval: 3000,
                    target: '+=1',
                    autostart: true
                })
            ;

        });

*/

        /*
        require(["jCarousel" ], function(  jCarousel  ) {

        });
        */




    </script>
