{# /** @var \Bluz\View\Layout $this */ #}

{# Меню для админки #}

<div class="navbar navbar-inverse navbar-fixed-top backend">
    <div class="navbar-inner">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand {% if(module('index')) %}active{% endif %}" href="{{ baseUrl('/') }}">{{ __('Keks.ik') }}</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="fa fa-bar"></span>
                    <span class="fa fa-bar"></span>
                    <span class="fa fa-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--li {% if(module('Index')) %}class="active"{% endif %}>
                        {{ ahref('Home', ['index', 'index']) }}
                    </li-->
					<li {% if(module('admin','categories')) %}class="active"{% endif %}>
                        {{ ahref('Категории', ['admin', 'categories']) }}
                    </li>
                    <li {% if(module('admin','products')) %}class="active"{% endif %}>
                        {{ ahref('Продукты', ['admin', 'products']) }}
                    </li>
                    <!--li {% if(module('blog','Base')) %}class="active"{% endif %}>
                        {{ ahref('Блог', ['блог', '']) }}
                    </li>
                    <li {% if(module('autor')) %}class="active"{% endif %}>
                        {{ ahref('Автор', ['автор', '']) }}
                    </li>
                    <li {% if(module('dashboard')) %}class="active"{% endif %}>
                      {{ ahref('Dashboard', ['dashboard', 'index']) }}
                    </li>
                    <li {% if(module('test')) %}class="active"{% endif %}>
                        {{ ahref('Test', ['test', '']) }}
                    </li-->
                </ul>

                {% if( user('info') ) %}
                {# if ($identity = $this->user()) #}

                    {% set info = user('info') %}

                    <p class="navbar-text navbar-right">

                        Logged in as {{   ahref(info.login, ['users', 'profile', {'id':info.id}] )  }}

                        ({{   ahref('Sign Out', ['users', 'signout'])  }})

                        {#
                           {{ ahref( user('info').login,['users', 'profile', [id:user('info').id] ]) }}
                        <?php echo __('Logged in as %s', $this->ahref($identity->login, array('users', 'profile', array('id' => $identity->id)))); ?>
                        (<?php echo  $this->ahref(__('Sign Out'), array('users', 'signout')); ?>)
                        #}
                    </p>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li>{{ ahref(__('Sign In'), ["users", "signin"] ) }}</li>
                    </ul>
                {% endif %}




                <div id="loading"></div>

                <div id="feedback-message"></div>


            </div>
            <p class="navbar-text navbar-left breadcrumbs back-end">
                {% if(breadCrumbs()) %}
                {% for crumb in breadCrumbs() %}
                {{ crumb }}
                {% if (loop.revindex != 1) %}
                {% if(loop.length > 1) %}
                —
                {% endif %}
                {% endif %}
                {% endfor %}
                {% endif %}
            </p>
        </div>
    </div>
</div>

