<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <title>{{ title(zoqa_title) }}</title>
    <base href="{{ baseUrl() }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="profile" href="http://gmpg.org/xfn/11"/>
    <link rel="stylesheet" href="{{ baseUrl('/public/css/bootstrap.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/price.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/styles.css') }}" />
    <link rel="stylesheet" href="{{ baseUrl('/public/css/print.css') }}" media="print" />
    <link rel="shortcut icon"  href="{{ baseUrl('/public/favicon.png') }}" type="image/png" />

    <script src="{{ baseUrl('/public/js/require.js') }}"></script>
    <script src="{{ baseUrl('/public/js/config.js') }}"></script>

    <!-----------------Юля-+++------------------------>
    {#
    <script src="{{ baseUrl('/public/js/scripts/script.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/custom_animations.js') }}"></script>
    <script src="{{ baseUrl('/public/js/scripts/custom_easing.js') }}"></script>
    #}
    <!------------------------------------------>

    <!-- For IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="{{ baseUrl('/public/js/vendor/html5shiv.js') }}"></script>
    <script src="{{ baseUrl('/public/js/vendor/html5shiv-printshiv.js') }}"></script>
    <![endif]-->

{{ headScript() }}
{{ headStyle() }}
{{ link() }}
{{ meta() }}

{{ trigger('header') }}
</head>
<body data-spy="scroll" data-bluz-module="{{ module() }}" data-bluz-controller="{{ controller() }}">

{% if( hasMessages() ) %} {# php if (app()->hasMessages()): #}
{# JS not allow read headers of current request, only for XMLHTTPRequests :( #}

    <script>
        require(['bluz.notify'], function(notify) {
            notify.set({{ getMessages() }} );
        });
    </script>
{% endif %}

