{% if(empty_basket) %}
<h4>Корзина пуста</h4>
<script>
    require(["jquery", "bluz.notify", "basket", "basic"], function ($, notify, basket, basic) {
        $(function () {
            basket.redrawCabinetWg()
        });
    });
</script>

{% else %}
<div class="wrapper-goods">
{% if(step != 4) %}
<div class="basket-controls basket-navigation">
    <div class="basket-btn-navi button-basket {% if(step == 1) %}active{% endif %}" data-step="1">Корзина</div>
    <div class="separator"></div>
    <div class="basket-btn-navi button-adress {% if(step == 2) %}active{% endif %}" data-step="2">Адрес</div>
    <div class="separator"></div>
    <div class="basket-btn-navi button-type-of-payment {% if(step == 3) %}active{% endif %}" data-step="3">Тип оплаты
    </div>
</div>
{% endif %}

<input type="hidden" name="step" value="{{ step }}">

{% if(step == 1) %}
{% if(products) %}
<table class="title">
    <tr>
        <td>Фото</td>
        <td>Наименование</td>
        <td>Цена</td>
        <td>Количество</td>
        <td>Стоимость</td>
        <td>Действия</td>
    </tr>
</table>
<div class="white basket-products">
    <table id="basket-items">
        {% for product in products %}
        <tr class="product-item" data-products_id="{{ product.products_id }}">
            <td>
                <div class="image-box"><img src="{{ baseUrl('public/images/goods1.jpg') }}"></div>
            </td>
            <td>{{ product.products_name }}</td>
            <td>{{ product.products_shoppingcart_price|round(2, 'ceil') }} грн.</td>
            <td>
                <input type="hidden" name="products_id" value="{{ product.products_id }}">
                <input type="hidden" name="products_shoppingcart_price"
                       value="{{ product.products_shoppingcart_price }}">

                <div class="number-arrow">
                    <div class="arrow dec"><img src="{{ baseUrl('public/images/arrow-dec.png') }}"></div>
                    <input type="number" min="1" value="{{ product.products_num }}" class="num">

                    <div class="arrow inc"><img src="{{ baseUrl('public/images/arrow-inc.png') }}"></div>
                </div>
            </td>
            <td><span class="products_total">{{ product.products_total }}</span> грн.</td>
            <td>
                <div class="remove_product">Удалить</div>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="basket-total-wrapper">
   <div class="box-1">
       Сумма: <span class="basket-total">{{ basket_total }}</span> грн
       </div>
</div>
    {% endif %}
    {% elseif(step == 2) %}

    <div class="white note">
        <h4 class="header-4">Адрес доставки</h4>
        <textarea id="address_dostavki">{{ address_dostavki }}</textarea>
    </div>
    <div class="white note">
        <h4 class="header-4">Пояснения к заказу</h4>
        <textarea id="order_notes">{{ order_notes }}</textarea>
    </div>
    {% elseif(step == 3) %}

    <div class="user-order-details">

        <br> Сумма: {{ total }}
        <br>
        {% if(total_discounted) %}
        Сумма со скидкой: {{ total_discounted|round(2, 'ceil') }}
        {% endif %}
        <br><br>
        {{ checkbox_group }}
    </div>

    {% elseif(step == 4) %}
    <div class="user-order-details">
        {#<span class="order-message">{{ new_order_mess }}</span>#}
        <h4>{{ new_order_mess }}</h4>

        {% if(new_orders_id) %}
        <p>Номер Вашего заказа: {{ new_orders_id }}</p>
        {% endif %}
        {% if(present) %}
        <p>{{ present }}</p>
        {% endif %}

        <h5>{{ message }}</h5>
    </div>
    {% endif %}


    {% if(step != 4) %}
    <div class="basket-controls basket-navigation-second">
        <!--button class="button-basket">В Каталог</button-->
        <button class="button-adress clear-basket"> Очистить Корзину</button>
        <a href="JavaScript:void(0);" data-next_step="{{ next_step }}" class="next_step button-type-of-payment">{{
            next_step_head }}</a>
    </div>
    {% endif %}
</div>
{% endif %}

<script>


require(["jquery", "bluz.notify", "basket", "basic"], function ($, notify, basket, basic) {
    $(function () {

         function updateBasket() {
            // TODO перенести в модуль
            basket.redrawCabinetWg(2);
            basket.recalcTotal()
        }

        $(".basket-btn-navi").off().on("click", function (e) {
            // TODO перенести в модуль
            var data = {}
            var url = "корзина"
            var target_step = $(this).attr("data-step") * 1
            var current_step = $("input[name=step]").val() * 1
            data["step"] = target_step

            if ($(this).hasClass("active")) return false;

            if (target_step > current_step)  return false;

            $.ajax({
                type: "POST",
                data: data,
                url: url,
                context: document.body,
                dataType: "html"
            }).done(function (response, status, responseObj) {
                    if (status == "success") {
                        $("#content_box").html(response)

                        if (responseObj.status != 200) {
                        } else {
                            if (current_step == 3) {
                                basket.redrawCabinetWg();
                            }
                        }
                    }
                });
        });

        $(".remove_product").on("click", function (e) {
            // TODO перенести в модуль
            var products_id = $(this).closest("tr").attr("data-products_id")

            var data = {}
            data["products_id"] = products_id
            data["mode"] = "remove"

            $.ajax({
                type: "POST",
                data: data,
                url: "basket/ajax/modify_basket",
                context: document.body,
                dataType: "json"
            }).done(function (response, status, responseObj) {

                    if (responseObj.responseJSON.redir == "clear") {
                        basket.clearBasket();
                    } else {
                        $("#basket-items tr[data-products_id=" + products_id + "]").hide();
                        basket.redrawCabinetWg(1);
                        basket.recalcTotal();
                    }
                });
        });

        $(".next_step").off()
            .on("click", function (e) {
                // TODO перенести в модуль
                // return basket.nextStep()

                var payment_types_id = $("input[name=payment_types_id]:checked").val()

                var next_step = $(this).attr("data-next_step");
                var step = $("input[name=step]").val() * 1

                var data = {}
                var url = "корзина"
                data["step"] = next_step

                if (step == 2) {
                    var address_dostavki = $("#address_dostavki").val()
                    data["address_dostavki"] = address_dostavki
                    data["order_notes"] = $("#order_notes").val()
                }

                if (step == 3) {
                    // Передать способ оплаты
                    if(payment_types_id == undefined){
                        basic.fastPopup("Ошибка","Выберите способ оплаты","width:500px;")
                        return false;
                    }
                    data["payment_types_id"] = payment_types_id
                }

                $.ajax({
                    type: "POST",
                    data: data,
                    url: url,
                    context: document.body,
                    dataType: "html"
                }).done(function (response, status, responseObj) {
                        $(this).addClass("done");
                        if (status == "success") {
                            $("#content_box").html(response)
                            /*
                             // responseObj.responseText - is response
                             if(response.response == "ok"){
                             ///console.log("ок")

                             // var $div = bluz_ajax.createModal("content") // не работает
                             } else {
                             // console.log("Ошибка данных")
                             }
                             */

                            if (responseObj.status != 200) {
                                // notify.addError("Error 404")
                            } else {
                                var data = {}
                                /* $.ajax({
                                 type: "POST",
                                 data: data,
                                 url: "users/ajax/get_credit",
                                 context: document.body,
                                 dataType: "json"
                                 }).done(function(response,status,responseObj) {
                                 $( this ).addClass( "done" );
                                 if(status == "success"){
                                 $("#users_credit").html(response.credit)
                                 }
                                 });
                                 */
                                if (step == 3) {
                                    basket.redrawCabinetWg();
                                }
                            }

                            // $("#article-items").append(response)
                        }
                    });

                return false;
            });

        $("input.num").off()
            .on("keypress", function (e) {
                var code = e.keyCode || e.which;

                if(code == 13){

                    var num = $(this).val()
                    var products_id = $(this).closest(".product-item").find("input[name=products_id]").val()

                    basket.updateProduct(products_id,num)

                    var products_shoppingcart_price = $(this).closest(".product-item").find("input[name=products_shoppingcart_price]").val()
                    $(this).closest(".product-item").find(".products_total").html(Math.round(products_shoppingcart_price * num * 100) / 100)

                    return false
                }
            });

        $(".arrow.inc").off()
            .on("click", function (e) {
                // TODO перенести в модуль
                var num = $(this).closest(".product-item").find("input.num").val();
                num++
                $(this).closest(".product-item").find("input.num").val(num)
                var products_shoppingcart_price = $(this).closest(".product-item").find("input[name=products_shoppingcart_price]").val()

                $(this).closest(".product-item").find(".products_total").html(Math.round(products_shoppingcart_price * num * 100) / 100)

                var data = {}
                var url = "basket/ajax/modify_basket"
                data["products_id"] = $(this).closest(".product-item").find("input[name=products_id]").val()

                data["mode"] = "update"
                data["products_num"] = num

                $.ajax({
                    type: "POST",
                    data: data,
                    url: url,
                    context: document.body,
                    dataType: "json"
                }).done(function (response, status, responseObj) {
                        // $(this).addClass("done");
                        if (status == "success") {
                            updateBasket()
                        }
                    });

                return false;
            });

        $(".arrow.dec").off()
            .on("click", function (e) {
                // TODO перенести в модуль
                var num = $(this).closest(".product-item").find("input.num").val();
                //num *= 1

                num--
                if (num < 0) num = 0;
                $(this).closest(".product-item").find("input.num").val(num)
                var products_shoppingcart_price = $(this).closest(".product-item").find("input[name=products_shoppingcart_price]").val()

                $(this).closest(".product-item").find(".products_total").html(Math.round(products_shoppingcart_price * num * 100) / 100)

                var data = {}
                var url = "basket/ajax/modify_basket"
                data["products_id"] = $(this).closest(".product-item").find("input[name=products_id]").val()


                data["mode"] = "update"
                data["products_num"] = num

                $.ajax({
                    type: "POST",
                    data: data,
                    url: url,
                    context: document.body,
                    dataType: "json"
                }).done(function (response, status, responseObj) {
                        if (status == "success") {
                            updateBasket()
                        }
                    });

                return false;
            });

        $(".clear-basket").off()
            .on("click", function (event, arrdata, textStatus, jqXHR) {
                basket.clearBasket()
                return false;
                /*
                 var data = {}
                 var url = "basket/ajax/modify_basket"

                 data["mode"] = "clear"

                 $.ajax({
                 type: "POST",
                 data: data,
                 url: url,
                 context: document.body,
                 dataType: "json"
                 }).done(function(response,status,responseObj) {
                 $( this ).addClass( "done" );
                 if(status == "success"){

                 if(response.response == "ok"){
                 ///console.log("ок")
                 //$("#basket-items").html("")

                 var data = {}
                 data["step"] = 1

                 $.ajax({
                 type: "POST",
                 data: data,
                 url: "корзина",
                 context: document.body,
                 dataType: "html"
                 }).done(function(response,status,responseObj) {
                 $( this ).addClass( "done" );
                 if(status == "success"){
                 $("#content_box").html(response)

                 if(responseObj.status != 200){
                 // notify.addError("Error 404")
                 }
                 }
                 });

                 } else {
                 // console.log("Ошибка данных")
                 }


                 if(responseObj.status != 200){
                 // notify.addError("Error 404")
                 }
                 }

                 basket.redrawCabinetWg(2);
                 });
                 */


            });

        /*
         // Если Я использую класс 'ajax'
         $("#ajax-callback-more")
         .on("success.ajax.bluz", function(event, data, textStatus, jqXHR){
         notify.addSuccess("Event `success.ajax.bluz` is fired");


         })
         .on("error.ajax.bluz", function(event, jqXHR, textStatus, errorThrown){
         notify.addSuccess("Event `error.ajax.bluz` is fired")
         });
         */

        /*
         $("#toggle-visibility")
         .on("success.ajax.bluz", function(event, data, textStatus, jqXHR){
         notify.addSuccess(data);

         setTimeout(function(){
         $("#feedback-message-2").html("");

         if( $("#toggle-visibility").hasClass("do-hide") ) {
         $("#toggle-visibility").addClass("do-unhide")
         $("#toggle-visibility").removeClass("do-hide")
         $("#toggle-visibility").text("{{ __("Открыть") }}");
         } else {
         $("#toggle-visibility").text("{{ __("Скрыть") }}");
         $("#toggle-visibility").removeClass("do-unhide")
         $("#toggle-visibility").addClass("do-hide")
         }
         },30);
         });

         // Если Я использую самостоятельный обработчик
         $("#ajax-callback-more").off().on("click",function(event, data, textStatus, jqXHR){

         var articles_frame_counter = $("input[name=articles_frame_counter]").val();
         var frame = $("input[name=frame]").val();

         var data = {}
         data["articles_frame_counter"] = articles_frame_counter; // frame number
         data["frame"] = frame; // frmae capacity
         data["uri"] = window.location.href;

         $.ajax({
         type: "POST",
         data: data,
         url: $(this).attr("href"),
         context: document.body,
         dataType: "html"
         }).done(function(response,status,responseObj) {
         $( this ).addClass( "done" );
         if(status == "success"){


         if(responseObj.status != 200){
         // notify.addError("Error 404")
         }

         articles_frame_counter = $("input[name=articles_frame_counter]").val();
         articles_frame_counter++;
         $("input[name=articles_frame_counter]").val(articles_frame_counter)

         $("#article-items").append(response)
         }
         });
         return false;
         });
         */

    });
});


</script>

