{% include 'partial/twig_header_front.phtml' %}




{% if(user()) %}
    {% include  'partial/twig_nav-bar.phtml' %}
{% endif %}

{% if(user('acl','system', 'Management')) %}
    {% include  'partial/twig_nav-bar.phtml' %}
{% else %}
    {# include  'partial/twig_navbar_front.phtml' #}
{% endif %}

<div>
{% include  'partial/twig_aside.phtml' %}
 <div class="content-wrapper">

    {% include  'partial/twig_aside_right.phtml' %}

    {% include  'partial/twig_content.phtml' %}


  <!--  <div class="container">
        <div class="row">

            {# ТЕСТЫ }

            {# Не пашет #}
            {{ Layout.test() }}

            {# Установка переменной #}
            {% set foo = '138' %}

            {{ request.get(1) }}

            {{ view.asd('set asd var') }}


            {# TODO проброс View в twig #}
            {% if (View.breadCrumbs)  %}
            <ul class="breadcrumb">
                <li>
                    <a href="/" class="bluz-tooltip" data-placement="bottom" data-original-title="{ __('Back to homepage') }">
                        <i class="fa fa-home"></i>
                        {  __('Home')  }
                    </a>
                </li>
                {for crump in View.breadCrumbs}

                    <li>
                        {crump}
                    </li>

                {endfor}
            </ul>
            {% endif %}
        </div>

        {{ getContent() }}-->

    </div>
    </div>
{% include 'partial/twig_footer.phtml' %}
</div>
