          <div class="wrapper-goods">
						<div class="basket-navigation">
							<div class="button-basket active">Корзина</div>
							<div class='separator'></div>
							<div class="button-adress">Адрес</div>
							<div class='separator'></div>
							<div class="button-type-of-payment">Тип оплаты</div>
						</div>							
						<table class='title'>
							<tr>
								<td>Фото</td>
								<td>Наименование</td>
								<td>Цена</td>
								<td>Количество</td>
								<td>Стоимость</td>
							</tr>
						</table>
						<div class='white'>							
							<table >
							<tr>
								<td><div class="image-box"><img src="images/goods1.jpg"></div></td>
								<td>Чай Ahmad Tea Английский к Завтраку</td>
								<td>25,56грн.</td>
								<td>
									<div class="number-arrow">
										<div class="dec"><img src="images/arrow-dec.png" ></div >
										<input type="number" min="1" value="1" class="num">										
										<div class="inc"><img src="images/arrow-inc.png"></div >
									</div>
								</td>
								<td>51,12грн.</td>
							</tr>
							<tr>
								<td><div class="image-box"><img src="images/goods1.jpg"></div></td>
								<td>Чай Ahmad Tea Английский к Завтраку</td>
								<td>25,56грн.</td>
								<td>
									<div class="number-arrow">
										<div class="dec"><img src="images/arrow-dec.png" ></div >
										<input type="number" min="1" value="1" class="num">										
										<div class="inc"><img src="images/arrow-inc.png"></div >
									</div>
								</td>
								<td>51000,12грн.</td>
							</tr>
						</table>
						</div>
						<h4>Примечание к заказу</h4>
						<div class='white note'>
							<textarea></textarea>
						</div>
						<div class="basket-navigation-second">
							<button class="button-basket">В Каталог</button>
							<button class="button-adress">Очистить Корзину</button>
							<button class="button-type-of-payment">Оформить Заказ</button>
						</div>                 
					</div>