<input type="hidden" name="is_search" value="{{ is_search }}">
<input type="hidden" name="search_text" value="{{ search_text }}">

{% if(product) %}
    <div>
        {{ product.products_name }}
        <input type="hidden" name="products_id" value="{{ product.products_id }}">
    </div>

{% elseif(products) %}

<div class="position-relative">
    <div class="select-cabnet"><span> Цена:   </span>
        <ul class="select-no-display">
            <li><a href="{{  baseUrl('catalog/products')}}" direction="asc" class="filter-price-order">по возрастанию </a></li>
            <li><a href="{{  baseUrl('catalog/products')}}" direction="desc" class="filter-price-order">по убыванию</a></li>
        </ul>
    </div>
</div>


    {{ widget('catalog','manufacturer',{'категория':categories_id,'manufacturers_id':manufacturers_id,'продукты':products_ids}) }}


<script>
    require(["jquery", "bluz.notify"], function($, notify) {
        $("a.filter-price-order").off().on("click",function(event, data, textStatus, jqXHR){

            var direction = $(this).attr("direction")
            var default_order_field =  $("form[name=state] input[name=default_order_field]").val()

            $("form[name=state] input[name=order]").val(direction + "-" + default_order_field)


            var data = {}

            data["direction"] = direction; //?

            var url = $(this).attr("href") + "?" + $("form[name=state]").serialize();

            var is_search = $("input[name=is_search]").val()

            if(is_search == 1){
                var text = $("input[name=search_text]").val()
                url = "поиск/" + text ;
                var manufacturers_id = $("form[name=state] input[name=filter-manufacturers_id]").val()
                data["manufacturers_id"] = manufacturers_id.substring(3)
            }

            $.ajax({
                type: "POST",
                data: data,
                url: url,
                context: document.body,
                dataType: "html"
            }).done(function(response,status,responseObj) {
                    $( this ).addClass( "done" );
                    if(status == "success"){

                        if(responseObj.status != 200){
                            notify.addError("Error 404")
                        }

                        $("#content_box").html(response)
                    }
                });

            return false;
        });

        $("a.filter-vendor").off().on("click",function(event, data, textStatus, jqXHR){


            var data = {}

            //data = $("form[name=state]").serialize();

            data["uri"] = window.location.href;
            data["manufacturers_id"] =  $(this).attr("manufacturers_id");
            data["категория"] = $(this).attr("categories_id");

            $("form[name=state] input[name=filter-manufacturers_id]").val("eq-" + data["manufacturers_id"]);
            $("form[name=state] input[name=filter-categories_id]").val("eq-" + data["категория"]);

            var url = $(this).attr("href") + "?" + $("form[name=state]").serialize();

            var is_search = $("input[name=is_search]").val()

            if(is_search == 1){
                var text = $("input[name=search_text]").val()
                url = "поиск/" + text ;
            }

            $.ajax({
                type: "POST",
                data: data,
                url: url,
                context: document.body,
                dataType: "html"
            }).done(function(response,status,responseObj) {
                    $( this ).addClass( "done" );
                    if(status == "success"){
                        /*
                         // responseObj.responseText - is response
                         if(response.response == "ok"){
                         // console.log("ок")
                         // var $div = bluz_ajax.createModal("content") // не работает
                         } else {
                         // console.log("Ошибка данных")
                         }
                         */

                        if(responseObj.status != 200){
                            notify.addError("Error 404")
                        }

                        //articles_frame_counter = $("input[name=articles_frame_counter]").val();
                        //articles_frame_counter++;
                        //$("input[name=articles_frame_counter]").val(articles_frame_counter)

                        //console.log(response)

                        $("#content_box").html(response)
                    }
                });
            return false;
        });
    });
</script>


<div class="wrapper-goods">

    {% for product in products %}

        <div class="goods">
            {% if( category_parent ) %} {% set parent = '/' ~ category_parent  %}
            {% else %} {% set parent = '' %} {% endif %}

            {% if( product.products_seo_page_name ) %} {% set product_link =   product.products_seo_page_name  %}
            {% else %} {% set product_link = product.products_id %} {% endif %}


            {#<div class="name">{{ ahref(  product.products_name, ['каталог' ~ parent ~ '/' ~ category_name, product_link]) }}</div>#}
            <div class="name">{{  product.products_name }}</div>
            <div class="image-box">
                <img src="{{ baseUrl('public/images/goods1.jpg') }}">
            </div>
            <div class="description">
                <div class="weight">{{ product.products_unit }}</div>
                <div class="cost">{{ product.products_shoppingcart_price|round(2, 'ceil') }}</div>
                <div class="basket"><a href="JavaScript:void(0);" data-href="ajax/modify_basket" class="push-to-basket" >В корзину</a></div>
                <div class="number-arrow">
                    <a class="dec" href="JavaScript:void(0);" data-href=""><img src="public/images/arrow-dec.png"></a>
                    <input type="number" min="1" value="1" class="num">
                    <a class="inc" href="JavaScript:void(0);" data-href=""><img src="public/images/arrow-inc.png"></a>
                </div>
                <div class="price">{{ product.products_shoppingcart_price|round(2, 'ceil') }}</div>
            </div>

            <input type="hidden" name="products_id" value="{{ product.products_id }}">
            <input type="hidden" name="products_barcode" value="{{ product.products_barcode }}">
            <input type="hidden" name="products_name" value="{{ product.products_name }}">
            <input type="hidden" name="products_unit" value="{{ product.products_unit }}">
            <input type="hidden" name="products_departament" value="{{ product.products_departament }}">
            <input type="hidden" name="products_shoppingcart_price" value="{{ product.products_shoppingcart_price }}">
            <input type="hidden" name="products_quantity" value="{{ product.products_quantity }}">
            {# <input type="hidden" name="products_price" value="{{ product.products_price }}"> #}



        </div>

    {% endfor %}
</div>
{% endif %}

<script>

    require(["jquery","bluz.notify","basket"],  function ($,notify,basket) {
        //notify.addSuccess("Event `success.ajax.bluz` is fired")
        //notify.add("success","asd")
        
         $(".goods a.dec").off()
                .on("click",function(e){
                    var num = $(this).closest(".goods").find("input.num").val();
                    num--
                    if( num < 0 ) num = 0;
                    
                    if(num == 0) return false;
                    
                    $(this).closest(".goods").find("input.num").val(num)
                    var products_shoppingcart_price = $(this).closest(".goods").find("input[name=products_shoppingcart_price]").val()

                    $(this).closest(".goods").find(".price").html( Math.round(products_shoppingcart_price * num * 100)/100 )

                    var data = {}
                    var url = "basket/ajax/modify_basket"
                    data["products_id"] = $(this).closest(".goods").find("input[name=products_id]").val()


                    data["mode"] = "update"
                    data["products_num"] = num

                    $.ajax({
                        type: "POST",
                        data: data,
                        url: url,
                        context: document.body,
                        dataType: "json"
                    }).done(function(response,status,responseObj) {
                            $( this ).addClass( "done" );
                            if(status == "success"){


                            }
                        });

                    return false;
                });
                
                $(".goods a.inc").off()
                .on("click",function(e){
                    var num = $(this).closest(".goods").find("input.num").val();
                    num++
                    
                    $(this).closest(".goods").find("input.num").val(num)
                    var products_shoppingcart_price = $(this).closest(".goods").find("input[name=products_shoppingcart_price]").val()

                    $(this).closest(".goods").find(".price").html( Math.round(products_shoppingcart_price * num * 100)/100 )

                    var data = {}
                    var url = "basket/ajax/modify_basket"
                    data["products_id"] = $(this).closest(".goods").find("input[name=products_id]").val()


                    data["mode"] = "update"
                    data["products_num"] = num

                    $.ajax({
                        type: "POST",
                        data: data,
                        url: url,
                        context: document.body,
                        dataType: "json"
                    }).done(function(response,status,responseObj) {
                            $( this ).addClass( "done" );
                            if(status == "success"){
                                basket.redrawCabinetWg(2);
                            }
                    });

                    return false;
                });

            $("a.push-to-basket").off().on("click", function(event, anydata, textStatus, jqXHR){
                var products_id = $(this).closest(".goods").find("input[name=products_id]").val();
                var products_num = $(this).closest(".goods").find("input.num").val();

                var data = {};
                data["products_id"] = products_id
                data["products_num"] = products_num
                data["mode"] = "add"

                $.ajax({
                    type: "POST",
                    data: data,
                    url: "basket/" + $(this).attr("data-href"),
                    context: document.body,
                    dataType: "json"
                }).done(function(response,status,responseObj) {
                        $( this ).addClass( "done" );
                        if(status == "success"){

                             // responseObj.responseText - is response
                             if(response.response == "ok"){

                                 basket.redrawCabinetWg(2);
                                //alert("Товар добавлен в корзину")

                             } else {
                                // console.log("Ошибка данных")
                             }


                            if(responseObj.status != 200){
                                // notify.addError("Error 404")
                            }

                            //$("#article-items").append(response)
                        }
                    });

                return false;
        });

    });

</script>
