<script>
    require(["bluz.grid"]);
</script>

<a class="btn btn-default show-addproduct-grid-btn" href="#" onclick="javascript: return false;">Добавить продукт</a>

<div class="clearfix" data-spy="grid" data-grid="{{ attribute(grid, 'getUid')  }}" data-url="my/grid-products/orders_id/{{ orders_id }}/operation/{{ operation }}" name="order_products_grid">

    {% if(operation == 'clone') %}
    {% else %}
        {{ partial('grid/filter-search.phtml', {'grid': grid}) }}


        <div class="input-group create-group pull-left">
            <a class="btn btn-primary pull-left dialog" data-ajax-method="get" href="admin/products-crud-2">Создать</a>
        </div>

        {{ partial('grid/limit.phtml', {'grid': grid}) }}
    {% endif %}

    <form name="order_management">
    <table class="table grid">
        <thead>
        <tr>
            {#<th width="60px"><a href="{{ grid.order('products_id', null, 'desc', false) }}">Артикул</a></th>#}
            <th width="100px"><a href="{{ grid.order('products_barcode') }}/orders_id/{{ orders_id }}/operation/{{ operation }}">Штрихкод</a></th>
            <th width="120px"><a href="{{ grid.order('products_name') }}/orders_id/{{ orders_id }}/operation/{{ operation }}">Наименование</a></th>
            {#<th width="20px"> <!--Картинка--> </th>#}
            <th width="80px"><a href="{{ grid.order('products_shoppingcart_price') }}/orders_id/{{ orders_id }}/operation/{{ operation }}">Цена, грн</a></th>
            <th width="120px"><a href="{{ grid.order('products_quantity') }}/orders_id/{{ orders_id }}/operation/{{ operation }}"> Количество </a></th>
            <th width="60px"><a href="{{ grid.order('products_num') }}/orders_id/{{ orders_id }}/operation/{{ operation }}">Сумма, грн</a></th>
            <th width="60px"></th>
        </tr>
        </thead>
        <tbody>
        {% for row in attribute(grid, 'getData') %}
        <tr class="visible-{{ row.products_visibility }}">
            {#<td class="grid-text">{{ row['products_id'] }}</td>#}
            <td class="grid-text">{{ row['products_barcode'] }}</td>
            <td class="grid-text">{{ row['products_name'] }}</td>
            {# <td>
                {% if(row['image_small']) %}
                <img src="{{ row['image_small'] }}" class="grid-image">
                {% endif %}
            </td> #}
            <td class="grid-text">

                {% if(operation == 'clone') %}
                    <span name="price">{{ round(row['products_shoppingcart_price']) }}</span>
                {% else %}

                {% endif %}
                <input class="product_price" type="hidden" name="product_price[{{ row['products_id'] }}]" value="{{ round(row['products_shoppingcart_price']) }}">

            </td>
            <td class="grid-text">
                {% if(operation == 'clone') %}
                    {# <input class="form-control grid-edit-field-1 update-item" type="text" value="{{ row['products_num']|round(2) }}" name="products_num" data-url="{{ url('orders','grid-products',{'orders_id':orders_id, 'gid':gid, 'products_id':row.products_id },true) }}" data-ajax-method="update" data-ajax-type="html" data-id="{{ row.products_id }}" data-fileld-name="products_num"> ({{ row['products_unit'] }}) #}

                    <input class="form-control grid-edit-field-2 products_number_field update-item" type="text"
                           data-fileld-name="products_num" data-id="{{ row.products_id }}"
                           data-ajax-type="html" data-ajax-method="update"
                           data-url="my/grid-products/orders_id/{{ orders_id }}/operation/{{ operation }}/products_id/{{ row['products_id'] }}"
                           name="products_num[{{ row['products_id'] }}]"
                           value="{{ row['products_num']|round(2) }}" >

                    <br/>({{ row['products_unit'] }})
                {% else %}

                {% endif %}
            </td>
            <td class="grid-text">
                {% if(operation == 'clone') %}
                    <span name="product_total">{{ (row['products_shoppingcart_price'] * row['products_num'])|round(2) }}</span>
                {% else %}

                {% endif %}
            </td>
            <td class="controls">

                {#
                <a href="{{ url('admin', 'products-crud', {'products_id' : row['products_id']}) }}" class="btn btn-xs btn-primary dialog" data-ajax-method="get">
                    <i class="fa fa-pencil"></i> Img
                </a>
                {% if( row.products_visibility == 1 ) %}
                {% set operation_hide = "hide" %}
                {% set operation_hide_style = "fa-lock" %}
                {% else %}
                {% set operation_hide = "unhide" %}
                {% set operation_hide_style = "fa-unlock" %}
                {% endif %}

                <a class="btn btn-xs btn-primary dialog" data-ajax-method="get" href="{{ url('admin', 'products-crud-2', {'products_id' : row['products_id']}) }}">
                    <i class="fa fa-pencil"></i> Edit
                </a>

                <a onclick="javascript:return false;" href="{{ url('admin','grid-products', {'products_id' : row['products_id'], 'operation': operation_hide} ) }}" class="hide-item"><i class="fa {{operation_hide_style}}"></i> </a>
                <!--a href="{{ url('test', 'crud', {'id' : row['id']}) }}" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                    <i class="fa fa-times"></i>
                </a-->
                #}

                {% if( operation == 'clone' ) %}
                    <a href="{{ url('my','grid-products',{'orders_id':orders_id, 'products_id':row.products_id, 'operation':operation },true) }}" onclick="javascript:return false" class="drop-item confirm btn btn-xs btn-danger ajax" data-ajax-method="delete" data-ajax-type="html" data-id="{{ row.products_id }}"><i class="fa fa-times"></i></a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul class="pager pull-left" style="display: none">
          <li>
              <a href="my/grid-products/orders_id/{{ orders_id }}/operation/{{ operation }}" class="filter show-all">{# __('Показать все продукты') #} </a>
          </li>
          <li>
          </li>
    </ul>

    <div id="order_total">
        Сумма: <span class="summ"></span> грн
    </div>

    {% if(operation == 'clone') %}

        <div style="clear: both;"></div>

        <div class="white note">
            <h4 class="header-4">Адрес доставки</h4>
            <textarea id="address_dostavki" name="address_dostavki">{{ address_dostavki }}</textarea>
        </div>
        <div class="white note">
            <h4 class="header-4">Телефон</h4>
            <input id="delivery_phone" name="delivery_phone" type="tel" value="{{ delivery_phone }}">
        </div>
        <div class="white note">
            <h4 class="header-4">Пояснения к заказу</h4>
            <textarea id="order_notes" name="order_notes">{{ order_notes }}</textarea>
        </div>
        <div class="white note">
            <h4 class="header-4">Дата доставки</h4>
            <input type="text" name="delivery_date" id="delivery_date" value="{{ delivery_date }}">
        </div>

        {{ checkbox_group }}

        <input type="hidden" name="orders_id" value="{{ orders_id }}">
    {% else %}
    {% endif %}

    </form>



    {% if(operation == 'clone') %}
    {% else %}
        {{ partial('grid/empty-rows.phtml', {'grid': grid}) }}
        {{ partial('grid/pagination.phtml', {'grid': grid}) }}
        {{ partial('grid/total.phtml', {'grid': grid}) }}
    {% endif %}

    <div class="input-group create-group pull-left">
        {#
        <a class="btn btn-primary pull-left bluz-tooltip load confirm" data-toggle="tooltip" data-original-title="Создать новый заказ" data-orders_id="{{ orders_id }}" data-ajax-target="#load" data-ajax-method="POST" data-ajax-type="html" href="my/clone">Клонировать заказ</a>
        {{ ahref('Loading', ['test', 'ajax-html'], {'class' : 'load btn btn-default', 'data-ajax-target' : '#order_total'}) }}
        #}
        {% if(operation == 'clone') %}
            <a href="#" _onclick="return false;" class="btn btn-primary pull-left clone_order">Клонировать заказ</a>
        {% else %}
        {% endif %}
    </div>

</div>

{% if(operation == 'clone') %}
<script>
    require(["jquery", "daterangepicker", "moment"], function ($, daterangepicker, moment) {

        var currentYear = moment().format("YYYY");
        var nextYear = currentYear * 1 + 1
        var minDate = "01/01/" + currentYear
        var maxDate = "31/12/" + nextYear

        $("input[name=delivery_date]").daterangepicker({
                format: "DD/MM/YYYY H:mm",
                singleDatePicker: true,
                startDate: moment(),
                endDate: moment(),
                minDate: minDate,
                maxDate: maxDate,
                dateLimit: { days: 60 },
                showDropdowns: true,
                showWeekNumbers: false,
                timePicker: true,
                timePickerIncrement: 1,
                timePicker12Hour: false,
                opens: "right",
                drops: "up",
                buttonClasses: ["btn", "btn-sm"],
                applyClass: "btn-primary",
                cancelClass: "btn-default",
                locale: {
                    applyLabel: "Выбрать",
                    cancelLabel: "Закрыть",
                    daysOfWeek: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
                    monthNames: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
                    firstDay: 1
                }
            },function (start, end, label) {

            }
        ).on("cancel.daterangepicker",function (ev, picker) {
                $(this).val(moment().format("DD/MM/YYYY H:mm"));
            }).on("apply.daterangepicker",function (ev, picker) {

            }).data("daterangepicker"); // .setStartDate("28/08/2016 16:21")

        $("input[name=delivery_date]").on("keypress", function () {
            return false;
        });
    });

    require(["jquery","basic"],  function ($,basic) {

        recalcSumm()
        initGrid()
        initBtn()

        function recalcSumm(){
            var grid = $("div[name=order_products_grid]");
            var total = 0
            $(grid).find("tr").each(function(){
                var produc_total = $(this).find("span[name=product_total]").text()
                if(produc_total != undefined && produc_total != ""){
                    produc_total *= 1
                    total += produc_total
                }
            });
            total = basic.round(total,2)
            $("div#order_total .summ").text(total)
        }

        function initGrid(){
            $("div[name=order_products_grid] tr").find("input.products_number_field").each(function(){
                $(this).on("keypress",function(e){
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        var num = $(this).val() * 1
                        var price = $(this).closest("tr").find("td span[name=price]").text()
                        var product_total = basic.round(num * price,2)

                        if(num < 0){
                            basic.fastPopup("Ошибка","Число не может быть отрицательным","width:500px;")
                            $(this).val("0")
                            return false;
                        }

                        $(this).closest("tr").find("td span[name=product_total]").text(product_total)
                        recalcSumm()
                    }
                })
            });
        }

        function initBtn(){
            $("a.clone_order").on("click",function(e){
                e.preventDefault()

                var url = "my/clone"
                var data = $("form[name=order_management]").serialize()
                var payment_types_id = $("input[name=payment_types_id]:checked").val()

                if(payment_types_id == undefined){
                    basic.fastPopup("Ошибка","Выберите способ оплаты","width:500px;")
                    return false;
                }

                $.ajax({
                    type: "POST",
                    data: data,
                    url: url,
                    context: document.body,
                    dataType: "html"
                }).done(function (response, status, responseObj) {
                        if (status == "success") {
                            $("#load").html(response)

                            if (responseObj.status != 200) {
                            } else {

                            }
                        }
                    });

                return false
            });
        }

        $("div[data-grid=add-products-sql]").on("reload",function(){
            // Обновилась грида добавления продуктов
            ////console.log("add_products_grid")
        });

        $("div[name=order_products_grid]").on("reload",function(){
            // Грида нового заказа обновилась

            recalcSumm()
            initGrid()
            initBtn()
        });

    });
</script>
{% endif %}

<div id="load"></div>

<script>
   require(["jquery", "bluz.notify"], function($, notify) {

              $("a.show-addproduct-grid-btn").on("click",function(){
                        if($(this).hasClass("visible")){
                               $(this).removeClass("visible")
                               $(this).text("Добавить продукт")
                               $("div.add-products-grid").hide()
                           } else {
                               $("div.add-products-grid").show()
                               $(this).addClass("visible")
                               $(this).text("Скрыть")
                           }
                   });

               $("div.add-products-grid").hide()
       });
</script>