<?php /** @var \Bluz\View\Layout $this */ ?>
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <title><?php echo $this->title(); ?></title>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="profile" href="http://gmpg.org/xfn/11"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/bootstrap.css'); ?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/font-awesome.css'); ?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/styles.css'); ?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/print.css'); ?>" media="print" />
    <link rel="icon"  href="<?php echo $this->baseUrl('favicon.ico'); ?>" type="image/png" />

    <script src="<?php echo $this->baseUrl('/public/js/require.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/public/js/config.js'); ?>"></script>

    <!-- For IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl('/public/js/vendor/html5shiv.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/public/js/vendor/html5shiv-printshiv.js'); ?>"></script>
    <![endif]-->

<?php echo $this->headScript();?>
<?php echo $this->headStyle();?>
<?php echo $this->link();?>
<?php echo $this->meta();?>

<?php $this->trigger('header'); ?>
</head>
<body data-spy="scroll" data-bluz-module="<?php echo $this->module(); ?>" data-bluz-controller="<?php echo $this->controller(); ?>">
<?php if (app()->hasMessages()):
    // JS not allow read headers of current request, only for XMLHTTPRequests :(
    ?>
    <script>
        require(['bluz.notify'], function(notify) {
            notify.set(<?php echo json_encode(app()->getMessages()->popAll()); ?>);
        });
    </script>
<?php endif; ?>
