<?php /** @var \Bluz\View\Layout $this */ ?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><?php echo __('Bluz'); ?></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="fa fa-bar"></span>
                    <span class="fa fa-bar"></span>
                    <span class="fa fa-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li <?php echo ($this->module('index')?'class="active"':''); ?>>
                        <?php echo $this->ahref('Home', array('index', 'index')); ?></li>
                    <li <?php echo ($this->module('dashboard')?'class="active"':'')?>>
                    <?php echo $this->ahref('Dashboard', array('dashboard', 'index')); ?></li>
                    <li <?php echo ($this->module('test')?'class="active"':'')?>>
                      <?php echo $this->ahref('Test', array('test', 'index')); ?></li>
                </ul>
                <?php if ($identity = $this->user()) : ?>
                    <p class="navbar-text navbar-right">
                        <?php echo __('Logged in as %s', $this->ahref($identity->login, array('users', 'profile', array('id' => $identity->id)))); ?>
                        (<?php echo  $this->ahref(__('Sign Out'), array('users', 'signout')); ?>)
                    </p>
                <?php else: ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><?php echo $this->ahref(__('Sign In') , array('users', 'signin')); ?></li>
                </ul>
                <?php endif; ?>
                <div id="loading"></div>
            </div>
        </div>
    </div>
</div>

