<h2 style="margin:100px">JS practice</h2>

<script>
    require(["jquery", "waterfall", "waterfall"], function($, waterfall, wf) {


        var count = 1;


        /**
         * Массив колбэков, который надо собирать вручную
         * [!] Имена полей строго соблюдать
         * @type {*[]}
         */
        var callbackArr = [
            {
                url: "my/grid-products/orders_id/117/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 01")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 02")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 03")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 04")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 05", waterfall.counter)
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 06")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 07")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 08")
                }
            },
            {
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "get",
                dataType: "html",
                success: function (data) {
                    console.log("call - 09")
                }
            }
        ];

        /**
         * [1] Формируем очередь
         */
        waterfall.queue = callbackArr;

        /**
         * [2] Задаем Финальный колбэк
         */
        waterfall.onDone = function () {
            console.log("onDone procesed", waterfall.counter,  wf.queue.length)

            // Новый водопад
            waterfall.add({
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "post",
                dataType: "html",
                success: function (data) {
                    console.log("call - 11")
                }})
                .add({
                    url: "test/ajax/sleep",
                    type: "post",
                    dataType: "html",
                    success: function (data) {
                        console.log("call - 12")
                    }});

            //waterfall.processParallel();

            var id;

            id = waterfall.push({
                url: "test/ajax/sleep",
                type: "post",
                dataType: "html",
                parentId: null,
                success: function (data) {
                    console.log("call - 20")
                }});


            id = waterfall.push({
                url: "my/grid-products/orders_id/118/operation/clone",
                type: "post",
                dataType: "html",
                parentId: id,
                success: function (data) {
                    console.log("call - 21")
                }});

            console.log(id)
        }

        /**
         * [3] Запускаем водопад
         */
        //waterfall.processParallel();








    });


</script>