{#
<!--div class="modal-header">
    <h3 class="modal-title"><?php echo $title; fb("Это шаблон index.phptml"); ?></h3>
</div>
<div class="modal-body">
    <p><?php echo $description; ?></p>
    <?php if (isset($message)): ?>
        <p><?php echo $message; ?></p>
    <?php endif; ?>
</div-->
#}
<div class="modal-header">
    <h3 class="modal-title">{{ title }}</h3>
</div>

<div class="modal-body">

    <p>{{ description }}</p>

    {% if message %}
         <p>{{ message }}</p>
    {% endif %}
</div>

